const genText = document.getElementById("gen-text")

genText.addEventListener("click", function() {
  let messages = [
    "dah la tu hopeless, Tuhan masih nak kau",
    "Imagine being so good looking, I could never",
    "tak, aku tak benci kau. jangan tanya benda sama dah",
    "thanks bagi hoodie",
    "thanks bagi hotwheels",
    "nasi goreng fish n chips, ais sirap limau ikat tepi",
    "never downgrade yourself",
    "chin up, always be proud of yourself",
    "thank you for the book",
    "one of the warmest person I've ever met",
    "jangan power sangat badminton, aku nak lagi power dari kau",
    "taktau pulak kau gay (gurau)",
    "stay annoying, don't ever be nonchalant",
    "jokes kau mantap",
    "don't hate yourself",
    "jangan speed up kalau stress, bahaya",
    "kita beza langit bumi, kau ambikla langit kalau nak sangat",
    "I would walk on thorns if the path leads to you",
    "Someone's name is my favourite word",
    "All the best on your career",
    "I could walk forever in a garden",
    "stay cool I think",
    "takpe malu, malu wajib ada. Baru ada maruah diri",
    "Don't lose your Lord",
    "A home in this very heart of mine",
    "I don't mind arguing if it's you",
    "Stay being oyen",
    "Jom makan sukiya, siapa laki dia bayar",
    "25th June. Lambat do bday kau",
    "As if the shadow could forget its figure",
    "Once get called as abang paris. ew/j",
    "asalkan kau bahagia kan",
    "Don't let altitude change your attitude (cool do quote ni) ",
    "Imagine being jealous over my girl bestfriend",
    "kau lagi selek dari aku",
    "Stop questioning irrelevant things. Makin stress ada la",
    "Act like what you truly want",
    "Orang asli Putrajaya la ni",
    "'Penat la jadi hensem'. Nyampah aku tapi takpe layan je",
    "bro be like 'dasar budak bongsu' ",
    "Be kind but not weak",
    "Be humble but not timid",
    "Be thoughtful but not lazy",
    "Be proud but not arrogant",
    "Sorry for ever being a nuisance",
    "Sorry for being selfish nak mam",
    "Not gonna sorry for my personality though",
    "Always be patient. You'll get the best result",
    "Learn to let go of something you can't control",
    "When you're alone, mind your thoughts",
    "When you're with people, mind your tongue",
    "Rabbi zidnii 'ilma warzuqna fahma",
  ]
  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})
